// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV-aErq22aS-ymsN9woJL5Rukv-W4enEc',
    appId: '1:91847847634:web:6c8360c9e3ac897379870b',
    messagingSenderId: '91847847634',
    projectId: 'localfixapp-6d2a6',
    authDomain: 'localfixapp-6d2a6.firebaseapp.com',
    storageBucket: 'localfixapp-6d2a6.firebasestorage.app',
    measurementId: 'G-GP0LYDHMV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj6skHjgkOhr2D7j8Qlju-c8yfLmue8UY',
    appId: '1:91847847634:android:f1729f1bc58e0ac979870b',
    messagingSenderId: '91847847634',
    projectId: 'localfixapp-6d2a6',
    storageBucket: 'localfixapp-6d2a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtt_CjvtZaoh4AkXWCY8Wpn1Drrl5fV4Q',
    appId: '1:91847847634:ios:a9b1f71236aacd9479870b',
    messagingSenderId: '91847847634',
    projectId: 'localfixapp-6d2a6',
    storageBucket: 'localfixapp-6d2a6.firebasestorage.app',
    iosBundleId: 'com.example.localfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtt_CjvtZaoh4AkXWCY8Wpn1Drrl5fV4Q',
    appId: '1:91847847634:ios:a9b1f71236aacd9479870b',
    messagingSenderId: '91847847634',
    projectId: 'localfixapp-6d2a6',
    storageBucket: 'localfixapp-6d2a6.firebasestorage.app',
    iosBundleId: 'com.example.localfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV-aErq22aS-ymsN9woJL5Rukv-W4enEc',
    appId: '1:91847847634:web:f07f0028293d88fc79870b',
    messagingSenderId: '91847847634',
    projectId: 'localfixapp-6d2a6',
    authDomain: 'localfixapp-6d2a6.firebaseapp.com',
    storageBucket: 'localfixapp-6d2a6.firebasestorage.app',
    measurementId: 'G-EK2GQ6V8R9',
  );
}
